name: Snapshot docker build and push

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Snapshot Docker
    runs-on: ubuntu-22.04

    steps:
      - name: Write GITHUB_TOKEN to a file
        run: echo "${{ secrets.GITHUB_TOKEN }}" > github_token.txt

      - name: Check if the token file exists
        run: cat github_token.txt || echo "âŒ Token file not found!"

      - name: ğŸ“¦ Docker build and push
        id: release
        uses: pagopa/eng-github-actions-iac-template/global/docker-build-push@main #
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

