name: Snapshot docker build and push

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Snapshot Docker
    runs-on: ubuntu-22.04

    steps:
      - name: Set environment variable for Docker
        run: echo "REPO_PASSWORD=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: ðŸ“¦ Docker build and push
        id: release
        uses: pagopa/eng-github-actions-iac-template/global/docker-build-push@main #
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_build_args: "REPO_PASSWORD=${{ secrets.GITHUB_TOKEN }}"

